from config import *


HEIGHT_KEY = FRAME_HEIGHT//6
WIDTH_KEY = FRAME_WIDTH//15

VK = {
    '~': {'x': 0, 'y': 0, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '1': {'x': WIDTH_KEY * 1, 'y': 0, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '2': {'x': WIDTH_KEY * 2, 'y': 0, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '3': {'x': WIDTH_KEY * 3, 'y': 0, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '4': {'x': WIDTH_KEY * 4, 'y': 0, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '5': {'x': WIDTH_KEY * 5, 'y': 0, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '6': {'x': WIDTH_KEY * 6, 'y': 0, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '7': {'x': WIDTH_KEY * 7, 'y': 0, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '8': {'x': WIDTH_KEY * 8, 'y': 0, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '9': {'x': WIDTH_KEY * 9, 'y': 0, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '0': {'x': WIDTH_KEY * 10, 'y': 0, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '-': {'x': WIDTH_KEY * 11, 'y': 0, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '=': {'x': WIDTH_KEY * 12, 'y': 0, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'Backspace': {'x': WIDTH_KEY * 13, 'y': 0, 'w': WIDTH_KEY * 2, 'h': HEIGHT_KEY},
    'Tab': {'x': 0, 'y': HEIGHT_KEY, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'Q': {'x': WIDTH_KEY * 1, 'y': HEIGHT_KEY, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'W': {'x': WIDTH_KEY * 2, 'y': HEIGHT_KEY, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'E': {'x': WIDTH_KEY * 3, 'y': HEIGHT_KEY, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'R': {'x': WIDTH_KEY * 4, 'y': HEIGHT_KEY, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'T': {'x': WIDTH_KEY * 5, 'y': HEIGHT_KEY, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'Y': {'x': WIDTH_KEY * 6, 'y': HEIGHT_KEY, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'U': {'x': WIDTH_KEY * 7, 'y': HEIGHT_KEY, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'I': {'x': WIDTH_KEY * 8, 'y': HEIGHT_KEY, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'O': {'x': WIDTH_KEY * 9, 'y': HEIGHT_KEY, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'P': {'x': WIDTH_KEY * 10, 'y': HEIGHT_KEY, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '[': {'x': WIDTH_KEY * 11, 'y': HEIGHT_KEY, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    ']': {'x': WIDTH_KEY * 12, 'y': HEIGHT_KEY, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '\\': {'x': WIDTH_KEY * 13, 'y': HEIGHT_KEY, 'w': WIDTH_KEY * 2, 'h': HEIGHT_KEY},
    'CapsLk': {'x': 0, 'y': HEIGHT_KEY * 2, 'w': WIDTH_KEY * 2, 'h': HEIGHT_KEY},
    'A': {'x': WIDTH_KEY * 2, 'y': HEIGHT_KEY * 2, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'S': {'x': WIDTH_KEY * 3, 'y': HEIGHT_KEY * 2, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'D': {'x': WIDTH_KEY * 4, 'y': HEIGHT_KEY * 2, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'F': {'x': WIDTH_KEY * 5, 'y': HEIGHT_KEY * 2, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'G': {'x': WIDTH_KEY * 6, 'y': HEIGHT_KEY * 2, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'H': {'x': WIDTH_KEY * 7, 'y': HEIGHT_KEY * 2, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'J': {'x': WIDTH_KEY * 8, 'y': HEIGHT_KEY * 2, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'K': {'x': WIDTH_KEY * 9, 'y': HEIGHT_KEY * 2, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'L': {'x': WIDTH_KEY * 10, 'y': HEIGHT_KEY * 2, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    ';': {'x': WIDTH_KEY * 11, 'y': HEIGHT_KEY * 2, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '\'': {'x': WIDTH_KEY * 12, 'y': HEIGHT_KEY * 2, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'Enter': {'x': WIDTH_KEY * 13, 'y': HEIGHT_KEY * 2, 'w': WIDTH_KEY * 2, 'h': HEIGHT_KEY},
    'Shift': {'x': 0, 'y': HEIGHT_KEY * 3, 'w': WIDTH_KEY * 2, 'h': HEIGHT_KEY},
    'Z': {'x': WIDTH_KEY * 2, 'y': HEIGHT_KEY * 3, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'X': {'x': WIDTH_KEY * 3, 'y': HEIGHT_KEY * 3, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'C': {'x': WIDTH_KEY * 4, 'y': HEIGHT_KEY * 3, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'V': {'x': WIDTH_KEY * 5, 'y': HEIGHT_KEY * 3, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'B': {'x': WIDTH_KEY * 6, 'y': HEIGHT_KEY * 3, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'N': {'x': WIDTH_KEY * 7, 'y': HEIGHT_KEY * 3, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'M': {'x': WIDTH_KEY * 8, 'y': HEIGHT_KEY * 3, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    ',': {'x': WIDTH_KEY * 9, 'y': HEIGHT_KEY * 3, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '.': {'x': WIDTH_KEY * 10, 'y': HEIGHT_KEY * 3, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '/': {'x': WIDTH_KEY * 11, 'y': HEIGHT_KEY * 3, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '^': {'x': WIDTH_KEY * 12, 'y': HEIGHT_KEY * 3, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'CtZ': {'x': WIDTH_KEY * 13, 'y': HEIGHT_KEY * 3, 'w': WIDTH_KEY * 2, 'h': HEIGHT_KEY},
    'Copy': {'x': 0, 'y': HEIGHT_KEY * 4, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'Paste': {'x': WIDTH_KEY, 'y': HEIGHT_KEY * 4, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'Cut': {'x': WIDTH_KEY * 2, 'y': HEIGHT_KEY * 4, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    ' ': {'x': WIDTH_KEY * 3, 'y': HEIGHT_KEY * 4, 'w': WIDTH_KEY * 5, 'h': HEIGHT_KEY},
    'Win': {'x': WIDTH_KEY * 8, 'y': HEIGHT_KEY * 4, 'w': WIDTH_KEY * 2, 'h': HEIGHT_KEY},
    'CtA': {'x': WIDTH_KEY * 10, 'y': HEIGHT_KEY * 4, 'w': WIDTH_KEY * 2, 'h': HEIGHT_KEY},
    '<': {'x': WIDTH_KEY * 12, 'y': HEIGHT_KEY * 4, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '\\/': {'x': WIDTH_KEY * 13, 'y': HEIGHT_KEY * 4, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    '>': {'x': WIDTH_KEY * 14, 'y': HEIGHT_KEY * 4, 'w': WIDTH_KEY, 'h': HEIGHT_KEY},
    'Settings': {'x': 0, 'y': HEIGHT_KEY * 5, 'w': WIDTH_KEY * 2, 'h': HEIGHT_KEY},
    '': {'x': WIDTH_KEY * 2, 'y': HEIGHT_KEY * 5, 'w': WIDTH_KEY * 12, 'h': HEIGHT_KEY},
    'Exit': {'x': WIDTH_KEY * 14, 'y': HEIGHT_KEY * 5, 'w': WIDTH_KEY, 'h': HEIGHT_KEY}
}
